### ISSUE TITLE
Instructions typo?

### ISSUE THREAD

**Issue by BaturalNoobs** [nightswimmer/nightswimmer.github.io#1]
First off - this is amazing. Thank you. I have a question about the Instructions, which say:

> - `# represents a rune room`
> - `$ represents an orb room`
...
> Example: You start in the yellow orb room. You move south, south, south, south, west, south, west, west and you arrive at the green rune room. You would input #YSSSSWSWW#G.

Since `$ represents an orb room`:

1. Should it say "You start in the yellow rune room" instead of "You start in the yellow orb room"?
2. Or should the first two letters of this input be `$Y` instead of `#Y` because it's a yellow orb room and not a yellow rune room?

Thanks again and I look forward to hearing back from you.

**Comment by nightswimmer** [comment]
Yes you are right, there was a typo, the first room should be $Y. It is corrected now. :)
