### ISSUE TITLE
Heya!

### ISSUE THREAD

**Issue by g0dkar** [nightswimmer/nightswimmer.github.io#2]
I'll go straight to the point: I'm tired asf right now from doing the Maze, it took me about 5h because I'm dumb asf. Do you accept donations? If so, where can I donate some cash to you? I am way beyond words of grateful for your tool.

Absolutely stellar and amazing work. And thanks for keeping it up all this time :)

From a Open Source contributor to another, thanks mate! I'm serious about the donation tho :')

Opening an issue because I think it'll have the best chance of being noticed ;)

**Comment by nightswimmer** [comment]
Hey man. Thank you for the comments, I never got much feedback back in the days where I made it. It's nice to know that people are still using it these days! :D No need for any donations, I made it for fun, to help myself and other fellow grinders in WOW. Just enjoy your mount! ;)

**Comment by g0dkar** [comment]
Thanks a lot mate, I found it on DuckDuckGo of all places and it was an AMAZING tool, leagues ahead of any other I found!

I'm a huge supporter of open source, and I'm very grateful for all the help I get from its community ^^

I'll close the issue just to keep it tidy! Thanks a million times <3

The mount is amazing, the best unicorn in the game ^^
